services:
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend-node/.env
    volumes:
      - ./backend-node/src:/app/src
      - ./backend-node/package.json:/app/package.json
      - ./backend-node/package-lock.json:/app/package-lock.json
    command: npm run dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
    command: npm run dev
