version: "3.8"

services:
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # env_file:
    #   - ./backend-node/.env
    volumes:
      - ./backend-node/src:/app/src
    command: npm run dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:3001/api/node/iam
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev
    # command: >
    #     sh -c "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run dev"
