version: "3.8"

services:
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend-node/.env
    volumes:
      - ./backend-node/src:/app/src
    command: npm run dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    command: >
        sh -c "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run dev"
